AllCops:
  NewCops: enable
  Exclude:
    - 'downloaded_images/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true

Layout/RedundantLineBreak:
  InspectBlocks: true
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Gemspec/DependencyVersion:
  Enabled: true

Style/RequireOrder:
  Enabled: true

Style/Documentation:
  Enabled: false